name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Odin
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2025-07

      - name: Install MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install SDL3 from source
        run: |
          git clone --depth 1 --branch release-3.2.18 https://github.com/libsdl-org/SDL.git
          mkdir SDL/build
          cd SDL/build
          cmake .. -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/sdl-install -DSDL_STATIC=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --parallel
          cmake --install . --config Release
        shell: bash

      - name: Build debug
        run: |
          odin run bild

      - name: Move files for uploading
        shell: bash
        run: |
          mkdir dist
          mv build/debug* dist/

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: loom-${{ matrix.os }}
          path: |
            dist/*
